# Место появление в лобби
lobby_respawn: "1,1,1"

# Место спавна во время игры
play_respawn: "1,1,1"

# Максимальное время игры (В минутах)
playing_time: 30

# Максимальное количество игроков для игры
max_players: 2

# Минимальная кордината Y после которой игрока автоматически убьет
min_y_to_death: 64

# Позиции от которых плагин будет отталкиваться при спавне контента для мини-игр
interact_poses:
  - "1,1,1"